swoole:
  http_server:
    port: 9501
    host: 0.0.0.0
    running_mode: process
    socket_type: tcp
    ssl_enabled: false
    trusted_hosts: localhost,127.0.0.1
    trusted_proxies:
      - '*'
      - 127.0.0.1/8
      - 192.168.2./16

    # enables static file serving
    static: advanced
    # equals to:
    # ---
    # static:
    #     public_dir: '%kernel.project_dir%/public'
    #     strategy: advanced
    #     mime_types: ~
    # ---
    # strategy can be one of: (default) auto, off, advanced, default
    #   - off: turn off feature
    #   - auto: use 'advanced' when debug enabled or not production environment
    #   - advanced: use request handler class \K911\Swoole\Server\RequestHandler\AdvancedStaticFilesServer
    #   - default: use default swoole static serving (faster than advanced, but supports less content types)
    # ---
    # mime types registration by file extension for static files serving in format: 'file extension': 'mime type'
    # this only works when 'static' strategy is set to 'advanced'
    #
    #   mime_types:
    #       '*': 'text/plain' # fallback override
    #       customFileExtension: 'custom-mime/type-name'
    #       sqlite: 'application/x-sqlite3'

    # enables hot module reload using inotify
    hmr:
      enabled: auto
    # hmr enabled can be one of: off, (default) auto, inotify, external
    #   - off: turn off feature
    #   - auto: use inotify if installed in the system
    #   - inotify: use inotify
    #   - external: dump files included before server start to text files,
    # files are parsed and used in swoole entrypoint command to decide if hard/soft reload is needed
    # files location, usually %kernel.cache_dir%/swoole_bundle/
    #
    #    hmr:
    #        enabled: external
    #        file_path: '%swoole_bundle.cache_dir%'

    # enables api server on specific port
    # by default it is disabled (can be also enabled using --api flag via cli)
    api: true
    # equals to:
    # ---
    # api:
    #     enabled: true
    #     host: 0.0.0.0
    #     port: 9200

    # additional swoole symfony bundle services
    services:

      # see: \K911\Swoole\Bridge\Symfony\HttpFoundation\TrustAllProxiesRequestHandler
      trust_all_proxies_handler: true

      # see: \K911\Swoole\Bridge\Symfony\HttpFoundation\CloudFrontRequestFactory
      cloudfront_proto_header_handler: true

      # see: \K911\Swoole\Bridge\Upscale\Blackfire\WithProfiler
      blackfire_profiler: false

      # see: \K911\Swoole\Bridge\Upscale\Blackfire\WithApm
      blackfire_monitoring: false

      # see: \K911\Swoole\Bridge\Tideways\Apm\WithApm
      tideways_apm:
        enabled: true
        service_name: 'app_name' # service name for Tideways APM UI

      # enable swoole logging
      access_log:
        enabled: false
        # define custom format or use some from AccessLogFormatter
#        format: !php/const K911\Swoole\Bridge\Log\AccessLogFormatter::FORMAT_COMMON_TIME
        # whatever register monolog line formatter service
        register_monolog_formatter_service: true
        # service id, can be used in monolog -> handlers -> formatter
        monolog_formatter_service_name: 'monolog.formatter.line.swoole.access_log'
        # custom line formatter format, extra section is used by monolog processors
        monolog_formatter_format: "%%message%% %%context%% %%extra%%\n"

    # swoole http server settings
    # see https://openswoole.com/docs/modules/swoole-server/configuration
    settings:
      # user and group for worker and task worker child processes
      # user: some-user
      # group: some-group

      reactor_count: 2
      worker_count: 4
      # when not set, swoole sets these are automatically set based on count of host CPU cores

      log_level: auto
      # can be one of: (default) auto, debug, trace, info, notice, warning, error
      #   - auto: when debug set to debug, when not set to notice
      #   - {debug,trace,info,notice,warning,error}: see swoole configuration

      log_file: '%kernel.logs_dir%/swoole_%kernel.environment%.log'
      pid_file: /var/run/swoole_http_server.pid

      buffer_output_size: 2097152
      # in bytes, 2097152b = 2 MiB

      package_max_length: 8388608
      # in bytes, 8388608b = 8 MiB

      worker_max_request: 0
      # integer >= 0, indicates the number of requests after which a worker reloads automatically
      # This can be useful to limit memory leaks
      worker_max_request_grace: ~
      # 'grace period' for worker reloading. If not set, default is worker_max_request / 2. Worker reloads
      # after 'worker_max_request + rand(0,worker_max_request_grace)' requests

  task_worker: # task workers' specific settings
    services:
      reset_handler: true # default true, set to false to disable services resetter on task processing end
    settings:
      worker_count: 2 # one of: positive number, "auto", or null to disable creation of task worker processes (default: null)
  platform:
    coroutines:
      enabled: false
      # default false. when enabled, swoole coroutine hooks for IO apis get activated
      # (https://openswoole.com/docs/modules/swoole-coroutine-enableCoroutine) and all stateful services
      # are being used in contextual way with multiple instances for each service
      # (https://openswoole.com/article/isolating-variables-with-coroutine-context)
      max_coroutines: 100
      # default value is 100000, if not set
      # (https://openswoole.com/docs/modules/swoole-server/configuration#max_coroutine)
      max_concurrency: 100
      # default value is null, if not set
      # it helps limitting this number, so you can be sure, that there is a limited amount of proxified service instances
      # (https://openswoole.com/article/v4-7-1-released)
      max_service_instances: 100
      # default is the same as max_concurrency, if not set, or max_coroutines if max_concurrency is not set
      # it is important to limit the amount of stateful service instances, that need to be created,
      # otherwise there would be at least so many service instances as coroutines, which might be quite enough
      # regarding how much coroutines can be run concurrently (e.g. 100000)
      # this number is by default equal to max_concurrency or max_coroutines, since it doesn't make sense to have
      # more stateful services than coroutines, but sometimes it might have sense to have less instances (e.g. if max_coroutines is too high)
      stateful_services:
        - SomeStatefulServiceId
          # add stateful service ids which need to be proxified and the bundle cannot detect them alone
        # check the section below about coroutines usage
      compile_processors:
        - class: ProcessorClass1
          priority: 10
          config: [] # all data will be propagated to the processor constructor, this attribute is not needed
        - ProcessorClass2 # default priority
          # register classes implementing the CompileProcessor interface
        # check the section below about coroutines usage
      # configuration options for doctrine processor - set instance limits for each connection type, or global limit
      doctrine_processor_config:
        # max connections in each swoole process for each doctrine connections, default is max_service_instances
        global_limit: 10
        limits:
          # connection with name 'default' will have max 9 instances per swoole process, if not set, default is global_limit
          default: 9