run:
  timeout: 5m
  go: "1.26.4"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert
    - gochecksumtype
    - gocognit
    - goconst
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - usetesting
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - exhaustruct
    - funlen
    - gocritic
    - gofumpt
    - gosimple
    - intrange
    - lll
    - mnd
    - perfsprint
    - prealloc
    - revive
    - err113
    - forbidigo
    - usestdlibvars

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - gosec
        - gocyclo
        - dupl
        - goconst
    - linters:
        - godox
      text: "TODO|FIXME"

linters-settings:
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  lll:
    line-length: 120
  goimports:
    local-prefixes: cargo.mleczki.pl
  varnamelen:
    min-name-length: 2
    ignore-names: ["w", "r", "i", "e"]
    ignore-decls: []
  misspell:
    ignore-words:
      - Nowe
      - Nowa

